---

#######################################
### CONTENT VIEW DEFAULTS
#######################################

# foreman_cv_allow_promote: false
# foreman_ccv_allow_promote: true
# foreman_ccv_auto_publish: true

### NGINX

# foreman_cv_allow_promote_nginx: "{{ foreman_cv_allow_promote | bool }}"

# foreman_cv_allow_promote_nginx_el7: "{{ foreman_cv_allow_promote_nginx | bool }}"
# foreman_cv_allow_promote_nginx_el8: "{{ foreman_cv_allow_promote_nginx | bool }}"
# foreman_cv_allow_promote_nginx_el9: "{{ foreman_cv_allow_promote_nginx | bool }}"
