---
# noqa: var-naming[no-role-prefix]
# defaults file for foreman_content_nginx

#######################################
### URLS
#######################################

### NGINX

foreman_repo_baseurl_nginx: https://nginx.org/packages

foreman_repo_baseurl_nginx_el7: "{{ foreman_repo_baseurl_nginx | default('https://nginx.org/packages') }}"
foreman_repo_baseurl_nginx_el8: "{{ foreman_repo_baseurl_nginx | default('https://nginx.org/packages') }}"
foreman_repo_baseurl_nginx_el9: "{{ foreman_repo_baseurl_nginx | default('https://nginx.org/packages') }}"


#######################################
### ENABLE VARS
#######################################

### NGINX

foreman_enable_nginx: false

foreman_enable_nginx_el7: false
foreman_enable_nginx_el8: "{{ foreman_enable_nginx | bool }}"
foreman_enable_nginx_el9: "{{ foreman_enable_nginx | bool }}"


#######################################
### PRODUCT DEFAULTS
#######################################

### NGINX

foreman_products_defaults_download_policy_nginx: "{{ foreman_products_defaults_download_policy }}"
foreman_products_defaults_mirroring_policy_nginx: "{{ foreman_products_defaults_mirroring_policy }}"
foreman_products_defaults_verify_ssl_on_sync_nginx: "{{ foreman_products_defaults_verify_ssl_on_sync | bool }}"
foreman_products_defaults_http_proxy_policy_nginx: "{{ foreman_products_defaults_http_proxy_policy }}"
foreman_products_defaults_unprotected_nginx: "{{ foreman_products_defaults_unprotected | bool }}"


#######################################
### ORGANIZATION VARS
#######################################

### NGINX

foreman_organization_nginx: "{{ foreman_organization }}"

foreman_organization_nginx_el7: "{{ foreman_organization_nginx }}"
foreman_organization_nginx_el8: "{{ foreman_organization_nginx }}"
foreman_organization_nginx_el9: "{{ foreman_organization_nginx }}"


#######################################
### CONTENT VIEW DEFAULTS
#######################################

### NGINX

foreman_cv_allow_promote_nginx: "{{ foreman_cv_allow_promote | bool }}"

foreman_cv_allow_promote_nginx_el7: "{{ foreman_cv_allow_promote_nginx | bool }}"
foreman_cv_allow_promote_nginx_el8: "{{ foreman_cv_allow_promote_nginx | bool }}"
foreman_cv_allow_promote_nginx_el9: "{{ foreman_cv_allow_promote_nginx | bool }}"


#######################################
### CONTENT
#######################################

foreman_content_credentials_nginx_main:
  - name: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-nginx"
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_nginx ~ '/keys/nginx_signing.key', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/nginx_signing.key') }}"

foreman_content_credentials_nginx: "{{ ( foreman_content_credentials_nginx_main | default([]) if foreman_enable_nginx | bool else [] ) |
  union( foreman_content_credentials_nginx_el7 | default([]) if foreman_enable_nginx_el7 | bool else [] ) |
  union( foreman_content_credentials_nginx_el8 | default([]) if foreman_enable_nginx_el8 | bool else [] ) |
  union( foreman_content_credentials_nginx_el9 | default([]) if foreman_enable_nginx_el9 | bool else [] )
  }}"

foreman_products_nginx_main: []
foreman_products_nginx: "{{ ( foreman_products_nginx_main | default([]) if foreman_enable_nginx | bool else [] ) |
  union( foreman_products_nginx_el7 | default([]) if foreman_enable_nginx_el7 | bool else [] ) |
  union( foreman_products_nginx_el8 | default([]) if foreman_enable_nginx_el8 | bool else [] ) |
  union( foreman_products_nginx_el9 | default([]) if foreman_enable_nginx_el9 | bool else [] )
  }}"

foreman_content_views_nginx_main: []
foreman_content_views_nginx: "{{ ( foreman_content_views_nginx_main | default([]) if foreman_enable_nginx | bool else [] ) |
  union( foreman_content_views_nginx_el7 | default([]) if foreman_enable_nginx_el7 | bool else [] ) |
  union( foreman_content_views_nginx_el8 | default([]) if foreman_enable_nginx_el8 | bool else [] ) |
  union( foreman_content_views_nginx_el9 | default([]) if foreman_enable_nginx_el9 | bool else [] )
  }}"

foreman_operatingsystems_nginx_main: []
foreman_operatingsystems_nginx: "{{ ( foreman_operatingsystems_nginx_main | default([]) if foreman_enable_nginx | bool else [] ) |
  union( foreman_operatingsystems_nginx_el7 | default([]) if foreman_enable_nginx_el7 | bool else [] ) |
  union( foreman_operatingsystems_nginx_el8 | default([]) if foreman_enable_nginx_el8 | bool else [] ) |
  union( foreman_operatingsystems_nginx_el9 | default([]) if foreman_enable_nginx_el9 | bool else [] )
  }}"

foreman_installation_media_nginx_main: []
foreman_installation_media_nginx: "{{ ( foreman_installation_media_nginx_main | default([]) if foreman_enable_nginx | bool else [] ) |
  union( foreman_installation_media_nginx_el7 | default([]) if foreman_enable_nginx_el7 | bool else [] ) |
  union( foreman_installation_media_nginx_el8 | default([]) if foreman_enable_nginx_el8 | bool else [] ) |
  union( foreman_installation_media_nginx_el9 | default([]) if foreman_enable_nginx_el9 | bool else [] )
  }}"

foreman_activation_keys_nginx_main: []
foreman_activation_keys_nginx: "{{ ( foreman_activation_keys_nginx_main | default([]) if foreman_enable_nginx | bool else [] ) |
  union( foreman_activation_keys_nginx_el7 | default([]) if foreman_enable_nginx_el7 | bool else [] ) |
  union( foreman_activation_keys_nginx_el8 | default([]) if foreman_enable_nginx_el8 | bool else [] ) |
  union( foreman_activation_keys_nginx_el9 | default([]) if foreman_enable_nginx_el9 | bool else [] )
  }}"

foreman_sync_plan_products_nginx_main:
  - "{{ foreman_product_name_prefix | default('') }}Nginx"

foreman_sync_plan_products_nginx: "{{ ( foreman_sync_plan_products_nginx_main | default([]) if foreman_enable_nginx | bool else [] ) |
  union( foreman_sync_plan_products_nginx_el7 | default([]) if foreman_enable_nginx_el7 | bool else [] ) |
  union( foreman_sync_plan_products_nginx_el8 | default([]) if foreman_enable_nginx_el8 | bool else [] ) |
  union( foreman_sync_plan_products_nginx_el9 | default([]) if foreman_enable_nginx_el9 | bool else [] )
  }}"

